package gr.uom.java.ast.decomposition;

public enum DifferenceType {
	AST_TYPE_MATCH,
	AST_TYPE_MISMATCH,
	EXPRESSION_NUMBER_MISMATCH,
	EXACT_MATCH,
	VARIABLE_TYPE_MISMATCH,
	VARIABLE_NAME_MISMATCH,
	LITERAL_VALUE_MISMATCH,
	LITERAL_TYPE_MISMATCH
}
