package gr.uom.java.ast.decomposition;

public enum DifferenceType {
	AST_TYPE_MISMATCH,
	ARGUMENT_NUMBER_MISMATCH,
	ARRAY_DIMENSION_MISMATCH,
	VARIABLE_TYPE_MISMATCH,
	VARIABLE_NAME_MISMATCH,
	METHOD_INVOCATION_NAME_MISMATCH,
	LITERAL_VALUE_MISMATCH,
	TYPE_COMPATIBLE_REPLACEMENT
}
